//! Serializable state model for the durable Navio downloader queue.
//!
//! These types are shared across three boundaries: Rust persistence,
//! Tauri-event payloads, and the TypeScript `DownloadJob` shape consumed by the
//! downloader page. Fields therefore favour stable, explicit primitives over
//! process-local handles. `DownloadRequest` preserves the original choices for
//! retry, while `DownloadJob` records only information that remains meaningful
//! after a restart.
//!
//! Status helpers encode the lifecycle contract: queued/preparing/downloading
//! jobs require a live process; paused, failed, and interrupted jobs retain
//! their staging directory and can resume; completed and cancelled jobs are
//! terminal. Adding a new status requires updating these helpers and the UI
//! action mapping so the two sides cannot silently disagree.

use std::time::{SystemTime, UNIX_EPOCH};

/// User-visible lifecycle state for one durable remote download.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Deserialize, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DownloadStatus {
  Queued,
  Preparing,
  Downloading,
  Paused,
  Completed,
  Failed,
  Cancelled,
  Interrupted,
}

impl DownloadStatus {
  /// Returns whether this state requires a live Navio process to make progress.
  pub fn is_active(self) -> bool {
    matches!(self, Self::Queued | Self::Preparing | Self::Downloading)
  }

  /// Returns the state to expose after Navio starts without a matching worker.
  pub fn recovered_after_restart(self) -> Self {
    if self.is_active() {
      Self::Interrupted
    } else {
      self
    }
  }

  /// Returns whether a user can resume the retained staging files.
  pub fn can_resume(self) -> bool {
    matches!(self, Self::Paused | Self::Failed | Self::Interrupted)
  }
}

/// Immutable user choices needed to repeat a download attempt safely.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DownloadRequest {
  pub url: String,
  pub format: String,
  pub no_playlist: bool,
}

/// Durable state and display data for a single Navio download.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DownloadJob {
  /// UUID generated by the renderer; it is also the private staging-folder name.
  pub id: String,
  /// Original choices are retained so Retry can reproduce the exact yt-dlp request.
  #[serde(flatten)]
  pub request: DownloadRequest,
  pub status: DownloadStatus,
  pub title: String,
  pub progress: f32,
  pub speed: String,
  pub eta: String,
  pub size: String,
  #[serde(default)]
  /// A user-facing, bounded diagnostic retained for failed/interrupted jobs.
  pub error: Option<String>,
  #[serde(default)]
  pub current_item: Option<u32>,
  #[serde(default)]
  pub total_items: Option<u32>,
  #[serde(default)]
  /// Final user-download paths are recorded only after the staging-to-download move succeeds.
  pub completed_paths: Vec<String>,
  pub created_at_ms: u64,
  pub updated_at_ms: u64,
}

impl DownloadJob {
  /// Builds the initial record before any asynchronous preparation begins.
  pub fn new(id: String, request: DownloadRequest) -> Self {
    let timestamp = now_ms();
    Self {
      id,
      request,
      status: DownloadStatus::Queued,
      title: "Preparing download...".to_string(),
      progress: 0.0,
      speed: "Queued".to_string(),
      eta: "—".to_string(),
      size: "—".to_string(),
      error: None,
      current_item: None,
      total_items: None,
      completed_paths: Vec::new(),
      created_at_ms: timestamp,
      updated_at_ms: timestamp,
    }
  }

  /// Records that a durable mutation changed the job.
  pub fn touch(&mut self) {
    self.updated_at_ms = now_ms();
  }
}

/// Produces a monotonic-enough wall-clock timestamp for local job ordering.
pub fn now_ms() -> u64 {
  SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .unwrap_or_default()
    .as_millis() as u64
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn active_statuses_recover_as_interrupted() {
    assert_eq!(
      DownloadStatus::Downloading.recovered_after_restart(),
      DownloadStatus::Interrupted
    );
    assert_eq!(
      DownloadStatus::Paused.recovered_after_restart(),
      DownloadStatus::Paused
    );
  }

  #[test]
  fn only_recoverable_states_can_be_queued_again() {
    assert!(DownloadStatus::Failed.can_resume());
    assert!(DownloadStatus::Interrupted.can_resume());
    assert!(DownloadStatus::Paused.can_resume());
    assert!(!DownloadStatus::Cancelled.can_resume());
    assert!(!DownloadStatus::Completed.can_resume());
  }
}
