use crate::library::MediaItem;
use serde::{Deserialize, Serialize};

/// A user-created playlist whose media metadata is independent of the library.
///
/// The `tracks` vector intentionally stores complete `MediaItem` values rather
/// than IDs. The library is allowed to forget a folder, rescan a file, or
/// rewrite its own database without changing what the user saved in a playlist.
/// This also lets an existing file remain playable after its source directory
/// is removed from the library page.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct Playlist {
  /// Stable identifier used by the frontend for rename/delete operations.
  ///
  /// IDs are generated by the frontend and validated for uniqueness by the
  /// backend before the playlist database is written.
  pub id: String,
  /// User-visible playlist name. Names are trimmed and compared
  /// case-insensitively during persistence validation.
  pub name: String,
  /// Ordered media snapshots saved in this playlist.
  ///
  /// The order is the playback order. A track can be removed from the library
  /// while its snapshot remains here; the player will discover that situation
  /// when it attempts to open the saved path.
  pub tracks: Vec<MediaItem>,
}

/// The persisted shape of `playlists.json`.
///
/// Keeping a wrapper object instead of serializing a bare array gives the file
/// room for future playlist-database metadata without changing the top-level
/// JSON contract.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct PlaylistsDb {
  /// All user-created playlists, retained in their database order.
  pub playlists: Vec<Playlist>,
}
